const validators = require('../validators');

test('isValidUsername', () => {
  expect(validators.isValidUsername(234)).toBe(false);
  expect(validators.isValidUsername('griffpatch')).toBe(true);
  expect(validators.isValidUsername('gr1fF_p4tch')).toBe(true);
  expect(validators.isValidUsername('griff patch')).toBe(false);
  expect(validators.isValidUsername(' griffpatch')).toBe(false);
  expect(validators.isValidUsername('abcdé')).toBe(false);
  expect(validators.isValidUsername('')).toBe(false);
  expect(validators.isValidUsername('e')).toBe(true);
  expect(validators.isValidUsername('ee')).toBe(true);
  expect(validators.isValidUsername('eee')).toBe(true);
  expect(validators.isValidUsername('e'.repeat(19))).toBe(true);
  expect(validators.isValidUsername('e'.repeat(20))).toBe(true);
  expect(validators.isValidUsername('e'.repeat(21))).toBe(false);
  expect(validators.isValidUsername(null)).toBe(false);
  expect(validators.isValidUsername(undefined)).toBe(false);
  expect(validators.isValidUsername(true)).toBe(false);
  expect(validators.isValidUsername(false)).toBe(false);
  expect(validators.isValidUsername([])).toBe(false);
  expect(validators.isValidUsername({})).toBe(false);

  // Test some normal usernames (non-Scratch Team)
  expect(validators.isValidUsername('griffpatch_tutor')).toBe(true);
  expect(validators.isValidUsername('-RISEN-')).toBe(true);
  expect(validators.isValidUsername('Coltroc')).toBe(true);
  expect(validators.isValidUsername('Blue_Science')).toBe(true);
  expect(validators.isValidUsername('atomicmagicnumber')).toBe(true);
  expect(validators.isValidUsername('JWhandle')).toBe(true);
  expect(validators.isValidUsername('josephjustin')).toBe(true);
  expect(validators.isValidUsername('UltraCoolGames')).toBe(true);
  expect(validators.isValidUsername('Hobson-TV')).toBe(true);
  expect(validators.isValidUsername('BoyMcBoy-')).toBe(true);
  expect(validators.isValidUsername('AquaLeafStudios')).toBe(true);
  expect(validators.isValidUsername('GarboMuffin')).toBe(true);
  expect(validators.isValidUsername('SullyBully')).toBe(true);
  expect(validators.isValidUsername('SapphireDemon-')).toBe(true);
  expect(validators.isValidUsername('AnExtremelyLongName')).toBe(true);
  expect(validators.isValidUsername('PotatoAnimator')).toBe(true);
  expect(validators.isValidUsername('EliMendez19Test')).toBe(true);
  expect(validators.isValidUsername('BESTERNOOB')).toBe(true);
  expect(validators.isValidUsername('cs123123123')).toBe(true);
  expect(validators.isValidUsername('Elec-citrus')).toBe(true);
  expect(validators.isValidUsername('yeetthehalls')).toBe(true);
  expect(validators.isValidUsername('KidArachnid')).toBe(true);
  expect(validators.isValidUsername('--FlamingGames--')).toBe(true);
  expect(validators.isValidUsername('Executec')).toBe(true);
  expect(validators.isValidUsername('Jethrochannz')).toBe(true);
  expect(validators.isValidUsername('DaBaconBossOfBosses')).toBe(true);
  expect(validators.isValidUsername('or2017')).toBe(true);
  expect(validators.isValidUsername('CANSLP')).toBe(true);
  expect(validators.isValidUsername('hfuller2953')).toBe(true);
  expect(validators.isValidUsername('Kraken265')).toBe(true);
  expect(validators.isValidUsername('Loev06')).toBe(true);
});